-- Flags e Selos
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS flag_destaque BOOLEAN DEFAULT FALSE;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS flag_novo_anuncio BOOLEAN DEFAULT FALSE;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS flag_exclusividade BOOLEAN DEFAULT FALSE;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS flag_off_market BOOLEAN DEFAULT FALSE;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS flag_lancamento BOOLEAN DEFAULT FALSE;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS flag_alto_padrao BOOLEAN DEFAULT FALSE;

-- Datas e Origem
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS data_publicacao TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS origem_cadastro TEXT;

-- Localizacao Detalhada
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS regiao TEXT;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS distrito TEXT;

-- Caracteristicas Estruturadas
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS estilo_arquitetonico TEXT;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS estrutura_construcao TEXT;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS tipo_piso JSONB DEFAULT '[]';
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS caracteristicas_terreno JSONB DEFAULT '[]';
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS vista JSONB DEFAULT '[]';
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS aquecimento JSONB DEFAULT '[]';
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS sistema_esgoto TEXT;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS abastecimento_agua TEXT;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS vagas_descricao TEXT;

-- Financeiro
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS impostos_anuais NUMERIC(15,2);

-- SEO e Marketing
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS seo_titulo TEXT;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS seo_descricao TEXT;
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]';

-- Corretores
ALTER TABLE imoveis ADD COLUMN IF NOT EXISTS corretores JSONB DEFAULT '[]';